repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: mix-format
        name: mix format
        entry: mix format
        language: system
        files: \.exs$
    -   id: mix-credo
        name: mix credo
        entry: mix credo
        language: system
        files: \.exs$
    -   id: mix-test
        name: mix test
        entry: mix test
        language: system
        files: apps/raffle_bot/test/.*_test\.exs$
