# fly.toml app configuration file generated for discord-raffle-bot on 2025-12-12T00:25:19+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-raffle-bot'
primary_region = 'ewr'
kill_signal = 'SIGTERM'
kill_timeout = '5s'
console_command = 'remote'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = "eval 'RaffleBot.Release.migrate()'"

[env]
  DATABASE_PATH = '/data/raffle.db'
  PHX_HOST = 'discord-raffle-bot.fly.dev'
  PHX_SERVER = 'true'
  PORT = '8080'

[processes]
  app = 'start'

[[mounts]]
  source = 'raffle_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024

[[metrics]]
  port = 9090
  path = '/metrics'
